import React, { createContext, useContext, useMemo, useState, useEffect } from "react";

const LanguageContext = createContext({
	language: "de",
	setLanguage: () => {},
	t: (key, fallback) => fallback || key,
});

const translations = {
	en: {

		"nav.home": "Home",
		"nav.programm": "Movies",
		"nav.cinemas": "Cinemas",
		"nav.cart": "Cart",
		"nav.snacks": "Snacks & Drinks",
		"nav.snacksShort": "Snacks",
		"nav.info": "Info & Help",
		"search.placeholder": "Search movie…",
		"search.aria": "Search movie",
		"notifications.label": "Notifications",
		"notifications.title": "Notifications",
		"notifications.empty": "No notifications",
		"notifications.markAllRead": "Mark all as read",
		"notifications.viewAll": "View all",
		"notifications.ticketReminder.title": "Ticket Reminder",
		"notifications.ticketReminder.message": "You have a showtime tomorrow at 8:00 PM",
		"notifications.promotion.title": "Special Discount",
		"notifications.promotion.message": "20% off on all tickets today!",
		"notifications.event.title": "New Movie",
		"notifications.event.message": "New movies in program.",
		"notifications.time.2hours": "2 hours ago",
		"notifications.time.5hours": "5 hours ago",
		"notifications.time.1day": "1 day ago",

		"home.heroTitle": "NOW IN CINEMA",
		"home.selectCity": "Select City",
		"home.selectDate": "Select Date",
		"home.showNearest": "Show Nearest Showtimes",
		"home.moviesTitle": "NOW IN CINEMA",
		"home.ticketsBuchen": "Buy Tickets",
		"home.favorite.add": "Add to favorites",
		"home.favorite.remove": "Remove from favorites",
		"home.slider.prev": "Previous slide",
		"home.slider.next": "Next slide",
		"home.noImage": "No image",

		"movies.nowShowing": "NOW SHOWING",
		"movies.comingSoon": "COMING SOON",
		"movies.tab.nowShowing": "Now Showing",
		"movies.tab.comingSoon": "Coming Soon",
		"movies.breadcrumb.home": "Home",
		"movies.breadcrumb.nowShowing": "Now Showing",
		"movies.breadcrumb.comingSoon": "Coming Soon",
		"movies.loading": "Loading…",
		"movies.empty": "No movies found in this category.",
		"movies.ticketsBuchen": "Buy Tickets",
		"movies.favorite.add": "Add to favorites",
		"movies.favorite.remove": "Remove from favorites",

		"moviedetail.vorstellungen": "Showtimes & Halls",
		"moviedetail.selectCinema": "Select Cinema",
		"moviedetail.selectDate": "Select Date",
		"moviedetail.searchShowtimes": "Search showtimes",
		"moviedetail.loading": "Loading showtimes…",
		"moviedetail.empty": "No showtimes found for this date.",
		"moviedetail.ticketsBuchen": "Buy Tickets",
		"moviedetail.favorite.add": "Add to favorites",
		"moviedetail.favorite.remove": "Remove from favorites",
		"moviedetail.back": "Back",
		"moviedetail.details": "Details",
		"moviedetail.readMore": "Read more",
		"moviedetail.readLess": "Less",
		"moviedetail.cta": "Secure your cinema tickets now!",
		"moviedetail.meta.release": "Release Date",
		"moviedetail.meta.genre": "Genre",
		"moviedetail.meta.duration": "Duration",
		"moviedetail.meta.ageRating": "Age Rating",
		"moviedetail.meta.noAgeRestriction": "No age restriction",
		"moviedetail.cast": "Cast",
		"moviedetail.cast.showAll": "Show all >",
		"moviedetail.cast.showLess": "Less",
		"moviedetail.cast.empty": "No cast information available.",
		"moviedetail.searchCinema": "Search cinema",
		"moviedetail.dateSelection": "Date selection",
		"moviedetail.next": "Next",
		"moviedetail.hall": "Hall",
		"moviedetail.comingSoon": "Coming Soon",
		"moviedetail.minutes": "Minutes",
		"moviedetail.ageRating.ab": "Aged {{age}}+",
		"moviedetail.ageRating.from": "From {{age}} years",
		"moviedetail.format.subtitled": "Subtitled",
		"moviedetail.format.subtitled3d": "3D / Subtitled",
		"moviedetail.format.3d": "3D",
		"moviedetail.cinema.fallback": "Cinema",

		"common.weekday.sunday": "Sunday",
		"common.weekday.monday": "Monday",
		"common.weekday.tuesday": "Tuesday",
		"common.weekday.wednesday": "Wednesday",
		"common.weekday.thursday": "Thursday",
		"common.weekday.friday": "Friday",
		"common.weekday.saturday": "Saturday",
		"common.weekday.short.sunday": "Sun",
		"common.weekday.short.monday": "Mon",
		"common.weekday.short.tuesday": "Tue",
		"common.weekday.short.wednesday": "Wed",
		"common.weekday.short.thursday": "Thu",
		"common.weekday.short.friday": "Fri",
		"common.weekday.short.saturday": "Sat",

		"common.date.today": "Today",
		"common.date.tomorrow": "Tomorrow",
		"common.date.dayAfterTomorrow": "Day after tomorrow",

		"cinemas.title": "Locations",
		"cinemas.subtitle": "Find our cinema locations near you",
		"cinemas.search.title": "SEARCH CINEMA",
		"cinemas.search.placeholder": "Enter city, postal code or cinema…",
		"cinemas.search.button": "Search",
		"cinemas.selectLabel": "Select location",
		"cinemas.allLocations": "All locations",
		"cinemas.card.filmeAnzeigen": "Show Movies",
		"cinemas.card.routeAnzeigen": "Show Route",
		"cinemas.map.title": "ALL CINEMAS ON THE MAP",
		"cinemas.map.hint": "Click on the markers for location details or use \"Show Route\" at a cinema.",
		"cinemas.loading": "Loading…",
		"cinemas.empty": "No cinemas found.",

		"seatselection.title": "Seat Selection",
		"seatselection.ticketauswahl": "Ticket Selection",
		"seatselection.cinema": "Cinema",
		"seatselection.date": "Date",
		"seatselection.time": "Time",
		"seatselection.ticketType": "Ticket Type",
		"seatselection.normal": "Normal",
		"seatselection.student": "Student",
		"seatselection.sitzplatz": "Seat",
		"seatselection.legend.free": "Available",
		"seatselection.legend.occupied": "Occupied",
		"seatselection.legend.selected": "Selected",
		"seatselection.legend.wheelchair": "Wheelchair",
		"seatselection.leinwand": "Screen",
		"seatselection.reihen": "Rows",
		"seatselection.plaetzeProReihe": "Seats per row",
		"seatselection.inWarenkorb": "Add to Cart",
		"seatselection.weiterCount": "Continue ({{count}})",
		"seatselection.zurueck": "Back",
		"seatselection.selectSeats": "Please select seats first.",
		"seatselection.ticketMismatch": "The total number of tickets (Normal + Student) must match the number of selected seats.",
		"seatselection.scrollRight": "Scroll seats to the right",

		"cart.title": "Your Tickets & Snacks",
		"cart.back": "Back",
		"cart.clear": "Clear All",
		"cart.empty.title": "Your cart is empty",
		"cart.empty.browse": "Browse Movies",
		"cart.remove": "Remove",
		"cart.quantity": "Quantity",
		"cart.total": "Total",
		"cart.checkout": "Checkout",
		"cart.gesamt": "Total",

		"payment.title": "Payment",
		"payment.back": "Back",
		"payment.cardNumber": "Card Number",
		"payment.expiryDate": "Expiry Date",
		"payment.cvv": "CVV",
		"payment.cardholderName": "Cardholder Name",
		"payment.bezahlen": "Pay",
		"payment.orderSummary": "Order Summary",
		"payment.total": "Total",
		"payment.empty": "Select date, showtime and seats first.",
		"payment.backToSeats": "Back to Seat Selection",
		"payment.error.formCheck": "Please check your details and fill in all required fields correctly.",
		"payment.error.cardNumberRequired": "Please enter your card number.",
		"payment.error.cardNumberLength": "Card number must be exactly 16 digits.",
		"payment.error.cardNumberDigits": "Card number may only contain digits.",
		"payment.error.expiryRequired": "Please enter the expiry date.",
		"payment.error.expiryFormat": "Use MM/YY format (e.g. 12/25).",
		"payment.error.expiryMonth": "Invalid month (01–12).",
		"payment.error.expiryExpired": "Card has expired.",
		"payment.error.cvvRequired": "Please enter the CVV.",
		"payment.error.cvvLength": "CVV must be exactly 3 digits.",
		"payment.error.cardholderRequired": "Please enter the cardholder name.",
		"payment.error.cardholderMin": "Name must be at least 2 characters.",
		"payment.error.cardholderLetters": "Name may only contain letters (no numbers or special characters).",

		"ticketsuccess.badge": "Payment successful",
		"ticketsuccess.title": "Your Ticket / Invoice",
		"ticketsuccess.print": "Print",
		"ticketsuccess.qr": "QR Code",
		"ticketsuccess.qrHide": "Hide QR",
		"ticketsuccess.myTickets": "My Tickets",
		"ticketsuccess.home": "Home",
		"ticketsuccess.email": "Tickets sent to email.",
		"ticketsuccess.artikel": "Item",
		"ticketsuccess.menge": "Quantity",
		"ticketsuccess.preis": "Price",
		"ticketsuccess.gesamtbetrag": "Total Amount",
		"ticketsuccess.ticketCode": "Ticket / Booking Code",
		"ticketsuccess.qrHint": "Scan at entrance – valid as ticket",

		"mytickets.title": "My Tickets",
		"mytickets.welcome": "Your bookings at a glance",
		"mytickets.loading": "Loading tickets…",
		"mytickets.error": "Tickets could not be loaded. Please try again later.",
		"mytickets.section.upcoming": "Upcoming Showings",
		"mytickets.section.menus": "My Menus & Snacks",
		"mytickets.empty.tickets": "No tickets yet",
		"mytickets.empty.ticketsSubtitle": "Book your next cinema experience.",
		"mytickets.empty.ticketsLink": "View Movies",
		"mytickets.empty.menus": "No menu orders yet",
		"mytickets.empty.menusSubtitle": "Snacks and drinks will appear here after purchase.",
		"mytickets.empty.menusLink": "Browse Snacks",
		"mytickets.toFilm": "To Movie",

		"favorites.title": "Favorites",
		"favorites.welcome": "Your watchlist",
		"favorites.loading": "Loading favorites…",
		"favorites.error": "Favorites could not be loaded. Please try again later.",
		"favorites.empty.title": "No favorites yet",
		"favorites.empty.subtitle": "Save movies to your watchlist.",
		"favorites.empty.link": "To program",
		"favorites.remove": "Remove from favorites",
		"favorites.bookTickets": "Book Tickets",

		"bookinghistory.title": "Booking History",
		"bookinghistory.welcome": "Past reservations and purchases.",
		"bookinghistory.loading": "Loading…",
		"bookinghistory.error": "Bookings could not be loaded. Please try again later.",
		"bookinghistory.empty.title": "No past bookings",
		"bookinghistory.empty.subtitle": "Completed cinema visits will appear here.",
		"bookinghistory.empty.link": "View Movies",
		"bookinghistory.loadingText": "Loading bookings…",
		"bookinghistory.errorText": "Booking History could not be loaded. Please try again later.",

		"usermenu.myAccount": "My Account",
		"usermenu.profile": "Profile",
		"usermenu.myTickets": "My Tickets",
		"usermenu.favorites": "Favorites",
		"usermenu.history": "Booking History",
		"usermenu.logout": "Logout",
		"usermenu.login": "Login",
		"usermenu.register": "Register",
		"usermenu.user": "User",
		"usermenu.info": "Info & Help",

		"profile.welcome": "Welcome, {{name}}",
		"profile.section.tickets": "Tickets & Bookings",
		"profile.tickets.desc": "View and manage your booked cinema tickets",
		"profile.history.desc": "Past reservations and purchases",
		"profile.section.account": "Account",
		"profile.favorites.desc": "Saved movies and watchlist",

		"common.min": "Min.",
		"common.eur": "€",
		"common.back": "Back",
		"common.continue": "Continue",
		"common.cancel": "Cancel",
		"common.save": "Save",
		"common.delete": "Delete",
		"common.edit": "Edit",
		"common.close": "Close",
		"common.loading": "Loading…",
		"common.error": "An error occurred",

		"footer.copyright": "© 2026 Demo Version by Orhan Yilmaz – all rights reserved; no commercial use.",

		"menu.addToCart": "Add to Cart",
		"menu.extraGrosses.name": "Extra Large Menu",
		"menu.extraGrosses.description": "Extra large menu with drink",
		"menu.extra.name": "Extra Menu",
		"menu.extra.description": "Extra menu with drink",
		"menu.grosses.name": "Large Menu",
		"menu.grosses.description": "Large menu with drink",
		"menu.kinder.name": "Kids Menu",
		"menu.kinder.description": "Kid-friendly menu",
		"menu.rioSanto.name": "Rio Santo Menu",
		"menu.rioSanto.description": "Rio Santo special menu",
		"menu.drink.description": "Menu with drink",
		"menu.drinks.cocaCola": "Coca Cola",
		"menu.drinks.fanta": "Fanta",
		"menu.drinks.fruchtsaft": "Fruit Juice",
		"menu.drinks.iceTea": "Ice Tea",
		"menu.drinks.wasser": "Water",

		"help.title": "Info & Help",
		"help.subtitle": "We're happy to help with any questions.",
		"help.faq.title": "Frequently Asked Questions",
		"help.faq.ticketPurchase.question": "How do I purchase tickets?",
		"help.faq.ticketPurchase.answer": "Select a movie, choose your cinema, date and showtime, then select your seats. Add tickets to cart and proceed to payment.",
		"help.faq.payment.question": "What payment methods are accepted?",
		"help.faq.payment.answer": "We accept credit cards (Visa, Mastercard) and debit cards. Payment is processed securely.",
		"help.faq.cancellation.question": "Can I cancel or refund my tickets?",
		"help.faq.cancellation.answer": "Tickets can be cancelled up to 2 hours before the showtime. Refunds are processed within 5-7 business days.",
		"help.faq.seats.question": "How do I select seats?",
		"help.faq.seats.answer": "After selecting a showtime, you'll see the seat map. Click on available seats to select them. You can select up to 6 seats per booking.",
		"help.faq.membership.question": "What is CinemoR Club?",
		"help.faq.membership.answer": "CinemoR Club is our loyalty program. Members earn points with every purchase and receive exclusive benefits and discounts.",
		"help.contact.title": "Contact Us",
		"help.contact.email.title": "Email",
		"help.contact.phone.title": "Phone",
		"help.contact.phone.hours": "Mon–Sun: 9:00 AM – 10:00 PM",
		"help.contact.address.title": "Address",
		"help.contact.hours.title": "Opening Hours",
		"help.contact.hours.content": "Mon–Sun: 10:00 AM – 12:00 AM",
		"help.support.title": "Support",
		"help.support.description": "Need more help? Check your account or contact our support team.",
		"help.support.myTickets": "My Tickets",
		"help.support.bookingHistory": "Booking History",
		"help.support.profile": "My Profile",

		"login.title": "Login",
		"login.subtitle": "Don't have an account yet?",
		"login.registerLink": "Register now",
		"login.email": "Email",
		"login.password": "Password",
		"login.showPassword": "Show password",
		"login.hidePassword": "Hide password",
		"login.forgotPassword": "Forgot password?",
		"login.submit": "Login",
		"login.loading": "Loading...",
		"login.error": "Login failed",
		"login.guestPurchase": "Or purchase tickets without registration",
		"login.noAccount": "Don't have an account yet?",
		"login.registerNow": "Register now for free",

		"register.title": "CinemoR ID REGISTRATION",
		"register.subtitle": "Already have a CinemoR ID?",
		"register.loginLink": "Login here",
		"register.requiredFields": "*Required fields",
		"register.firstName": "First Name",
		"register.lastName": "Last Name",
		"register.email": "Email",
		"register.password": "Password",
		"register.confirmPassword": "Confirm Password",
		"register.showPassword": "Show password",
		"register.hidePassword": "Hide password",
		"register.strongPassword": "Strong Password",
		"register.acceptTerms": "I accept the Terms and Conditions",
		"register.showTerms": "Show Terms and Conditions",
		"register.disclaimer": "This site uses hCaptcha. For more information, see \"Legal Notice\" or \"Privacy Policy\".",
		"register.submit": "Register now",
		"register.loading": "Loading...",
		"register.error.password": "Password must be at least 8 characters long and contain uppercase/lowercase letters, numbers and special characters.",
		"register.error.passwordMismatch": "Passwords do not match",
		"register.error.terms": "Please accept the Terms and Conditions",
		"register.error.failed": "Registration failed",

		"checkout.title": "Continue to Payment",
		"checkout.welcome": "Movie: {{movie}} · {{seats}} seat(s) · {{price}} €",
		"checkout.loggedIn": "Logged In",
		"checkout.continue": "Continue to Payment",
		"checkout.logout": "Logout",
		"checkout.choose": "How would you like to proceed?",
		"checkout.login": "Login",
		"checkout.loginDesc": "Login with email and proceed to payment",
		"checkout.register": "Register",
		"checkout.registerDesc": "Create new account, then pay",
		"checkout.guest": "Continue as Guest",
		"checkout.guestDesc": "Proceed to payment without account",
		"checkout.back": "← Back to Seat Selection",

		"forgotpassword.title": "Forgot Password",
		"forgotpassword.subtitle": "Enter your email address. We will send you a link to reset.",
		"forgotpassword.email": "Email Address",
		"forgotpassword.send": "Send Link",
		"forgotpassword.sending": "Sending...",
		"forgotpassword.success": "Email sent. Please check your inbox.",
		"forgotpassword.back": "Back to Login",
		"forgotpassword.error.failed": "Request failed. Please check email.",
		"forgotpassword.error.notFound": "This email address is not registered.",
		"forgotpassword.error.connection": "Connection error. Please try again later.",

		"resetpassword.title": "New Password",
		"resetpassword.subtitle": "Enter your new password (at least 6 characters).",
		"resetpassword.newPassword": "New Password",
		"resetpassword.confirmPassword": "Confirm Password",
		"resetpassword.save": "Save Password",
		"resetpassword.saving": "Saving...",
		"resetpassword.success": "Password has been changed. You can now log in.",
		"resetpassword.back": "Back to Login",
		"resetpassword.requestNew": "Request New Link",
		"resetpassword.error.invalid": "Invalid link. Please request a new link.",
		"resetpassword.error.mismatch": "Passwords do not match.",
		"resetpassword.error.short": "Password must be at least 6 characters.",
		"resetpassword.error.expired": "Link invalid or expired. Please request password again.",
		"resetpassword.error.connection": "Connection error. Please try again later.",

		"common.time": "",
		"common.user": "User",
		"common.loadingMovie": "Loading movie...",
		"common.loadingShowtimes": "Loading showtimes...",
	},
	de: {

		"nav.home": "Start",
		"nav.programm": "Filme",
		"nav.cinemas": "Kinos",
		"nav.cart": "Warenkorb",
		"nav.snacks": "Snacks & Getränke",
		"nav.snacksShort": "Snacks",
		"nav.info": "Info & Hilfe",
		"search.placeholder": "Film suchen…",
		"search.aria": "Film suchen",
		"notifications.label": "Benachrichtigungen",
		"notifications.title": "Benachrichtigungen",
		"notifications.empty": "Keine Benachrichtigungen",
		"notifications.markAllRead": "Alle als gelesen markieren",
		"notifications.viewAll": "Alle anzeigen",
		"notifications.ticketReminder.title": "Ticket-Erinnerung",
		"notifications.ticketReminder.message": "Sie haben morgen um 20:00 Uhr eine Vorstellung",
		"notifications.promotion.title": "Sonderrabatt",
		"notifications.promotion.message": "Heute 20% Rabatt auf alle Tickets!",
		"notifications.event.title": "Neuer Film",
		"notifications.event.message": "Neue Filme im Programm.",
		"notifications.time.2hours": "vor 2 Stunden",
		"notifications.time.5hours": "vor 5 Stunden",
		"notifications.time.1day": "vor 1 Tag",

		"home.heroTitle": "JETZT INS KINO",
		"home.selectCity": "Stadt auswählen",
		"home.selectDate": "Datum auswählen",
		"home.showNearest": "Nächste Vorstellungen anzeigen",
		"home.moviesTitle": "JETZT INS KINO",
		"home.ticketsBuchen": "Tickets buchen",
		"home.favorite.add": "Zu Favoriten hinzufügen",
		"home.favorite.remove": "Aus Favoriten entfernen",
		"home.slider.prev": "Vorherige Folie",
		"home.slider.next": "Nächste Folie",
		"home.noImage": "Kein Bild",

		"movies.nowShowing": "IM KINO",
		"movies.comingSoon": "BALD",
		"movies.tab.nowShowing": "Im Kino",
		"movies.tab.comingSoon": "Bald",
		"movies.breadcrumb.home": "Startseite",
		"movies.breadcrumb.nowShowing": "Im Kino",
		"movies.breadcrumb.comingSoon": "Bald",
		"movies.loading": "Wird geladen…",
		"movies.empty": "In dieser Kategorie wurden keine Filme gefunden.",
		"movies.ticketsBuchen": "Tickets buchen",
		"movies.favorite.add": "Zu Favoriten hinzufügen",
		"movies.favorite.remove": "Aus Favoriten entfernen",

		"moviedetail.vorstellungen": "Vorstellungen und Säle",
		"moviedetail.selectCinema": "Kino auswählen",
		"moviedetail.selectDate": "Datum auswählen",
		"moviedetail.searchShowtimes": "Vorstellungen suchen",
		"moviedetail.loading": "Vorstellungen werden geladen…",
		"moviedetail.empty": "Keine Vorstellungen für dieses Datum gefunden.",
		"moviedetail.ticketsBuchen": "Tickets buchen",
		"moviedetail.favorite.add": "Zu Favoriten hinzufügen",
		"moviedetail.favorite.remove": "Aus Favoriten entfernen",
		"moviedetail.back": "Zurück",
		"moviedetail.details": "Details",
		"moviedetail.readMore": "Mehr lesen",
		"moviedetail.readLess": "Weniger",
		"moviedetail.cta": "Sichern Sie sich jetzt Ihre Kinotickets!",
		"moviedetail.meta.release": "Kinostart",
		"moviedetail.meta.genre": "Genre",
		"moviedetail.meta.duration": "Laufzeit",
		"moviedetail.meta.ageRating": "FSK",
		"moviedetail.meta.noAgeRestriction": "ohne Altersbeschränkung",
		"moviedetail.cast": "Besetzung",
		"moviedetail.cast.showAll": "Alle anzeigen >",
		"moviedetail.cast.showLess": "Weniger",
		"moviedetail.cast.empty": "Keine Besetzung hinterlegt.",
		"moviedetail.searchCinema": "Kino suchen",
		"moviedetail.dateSelection": "Datumsauswahl",
		"moviedetail.next": "Nächste",
		"moviedetail.hall": "Saal",
		"moviedetail.comingSoon": "Demnächst",
		"moviedetail.minutes": "Minuten",
		"moviedetail.ageRating.ab": "ab {{age}} Jahren",
		"moviedetail.ageRating.from": "ab {{age}} Jahren",
		"moviedetail.format.subtitled": "Deutsch mit Untertiteln",
		"moviedetail.format.subtitled3d": "3D / Deutsch mit Untertiteln",
		"moviedetail.format.3d": "3D",
		"moviedetail.cinema.fallback": "Kino",

		"common.weekday.sunday": "Sonntag",
		"common.weekday.monday": "Montag",
		"common.weekday.tuesday": "Dienstag",
		"common.weekday.wednesday": "Mittwoch",
		"common.weekday.thursday": "Donnerstag",
		"common.weekday.friday": "Freitag",
		"common.weekday.saturday": "Samstag",
		"common.weekday.short.sunday": "So",
		"common.weekday.short.monday": "Mo",
		"common.weekday.short.tuesday": "Di",
		"common.weekday.short.wednesday": "Mi",
		"common.weekday.short.thursday": "Do",
		"common.weekday.short.friday": "Fr",
		"common.weekday.short.saturday": "Sa",

		"common.date.today": "Heute",
		"common.date.tomorrow": "Morgen",
		"common.date.dayAfterTomorrow": "Übermorgen",

		"cinemas.title": "Standorte",
		"cinemas.subtitle": "Finden Sie unsere Kino-Standorte in Ihrer Nähe",
		"cinemas.search.title": "KINO SUCHEN",
		"cinemas.search.placeholder": "Stadt, PLZ oder Kino eingeben…",
		"cinemas.search.button": "Suchen",
		"cinemas.selectLabel": "Standort wählen",
		"cinemas.allLocations": "Alle Standorte",
		"cinemas.card.filmeAnzeigen": "Filme anzeigen",
		"cinemas.card.routeAnzeigen": "Route anzeigen",
		"cinemas.map.title": "ALLE KINOS AUF DER KARTE",
		"cinemas.map.hint": "Klicken Sie auf die Marker für Standortdetails oder \"Route anzeigen\" bei einem Kino.",
		"cinemas.loading": "Laden…",
		"cinemas.empty": "Keine Kinos gefunden.",

		"seatselection.title": "Sitzplatzwahl",
		"seatselection.ticketauswahl": "Ticketauswahl",
		"seatselection.cinema": "Kino",
		"seatselection.date": "Datum",
		"seatselection.time": "Uhrzeit",
		"seatselection.ticketType": "Tickettyp",
		"seatselection.normal": "Normal",
		"seatselection.student": "Student",
		"seatselection.sitzplatz": "Sitzplatz",
		"seatselection.legend.free": "Frei",
		"seatselection.legend.occupied": "Besetzt",
		"seatselection.legend.selected": "Ausgewählt",
		"seatselection.legend.wheelchair": "Rollstuhl",
		"seatselection.leinwand": "Leinwand",
		"seatselection.reihen": "Reihen",
		"seatselection.plaetzeProReihe": "Plätze pro Reihe",
		"seatselection.inWarenkorb": "In den Warenkorb",
		"seatselection.weiterCount": "Weiter ({{count}})",
		"seatselection.zurueck": "Zurück",
		"seatselection.selectSeats": "Zuerst Plätze wählen.",
		"seatselection.ticketMismatch": "Die Gesamtanzahl der Tickets (Normal + Student) muss der Anzahl gewählter Plätze entsprechen.",
		"seatselection.scrollRight": "Sitze nach rechts scrollen",

		"cart.title": "Ihre Tickets & Snacks",
		"cart.back": "Zurück",
		"cart.clear": "Alle löschen",
		"cart.empty.title": "Ihr Warenkorb ist leer",
		"cart.empty.browse": "Filme durchsuchen",
		"cart.remove": "Entfernen",
		"cart.quantity": "Menge",
		"cart.total": "Gesamt",
		"cart.checkout": "Zur Kasse",
		"cart.gesamt": "Gesamt",

		"payment.title": "Zahlung",
		"payment.back": "Zurück",
		"payment.cardNumber": "Kartennummer",
		"payment.expiryDate": "Ablaufdatum",
		"payment.cvv": "CVV",
		"payment.cardholderName": "Karteninhaber",
		"payment.bezahlen": "Bezahlen",
		"payment.orderSummary": "Bestellübersicht",
		"payment.total": "Gesamtbetrag",
		"payment.empty": "Zuerst Datum, Vorstellung und Plätze wählen.",
		"payment.backToSeats": "Zurück zur Sitzplatzwahl",
		"payment.error.formCheck": "Bitte überprüfen Sie Ihre Angaben und füllen Sie alle Pflichtfelder korrekt aus.",
		"payment.error.cardNumberRequired": "Bitte geben Sie Ihre Kartennummer ein.",
		"payment.error.cardNumberLength": "Die Kartennummer muss genau 16 Ziffern haben.",
		"payment.error.cardNumberDigits": "Die Kartennummer darf nur Ziffern enthalten.",
		"payment.error.expiryRequired": "Bitte geben Sie das Ablaufdatum ein.",
		"payment.error.expiryFormat": "Bitte Format MM/JJ verwenden (z. B. 12/25).",
		"payment.error.expiryMonth": "Ungültiger Monat (01–12).",
		"payment.error.expiryExpired": "Die Karte ist abgelaufen.",
		"payment.error.cvvRequired": "Bitte geben Sie den CVV ein.",
		"payment.error.cvvLength": "CVV muss genau 3 Ziffern haben.",
		"payment.error.cardholderRequired": "Bitte geben Sie den Namen des Karteninhabers ein.",
		"payment.error.cardholderMin": "Der Name muss mindestens 2 Zeichen haben.",
		"payment.error.cardholderLetters": "Der Name darf nur Buchstaben enthalten (keine Zahlen oder Sonderzeichen).",

		"ticketsuccess.badge": "Zahlung erfolgreich",
		"ticketsuccess.title": "Ihr Ticket / Rechnung",
		"ticketsuccess.print": "Drucken",
		"ticketsuccess.qr": "QR-Code",
		"ticketsuccess.qrHide": "QR ausblenden",
		"ticketsuccess.myTickets": "Meine Tickets",
		"ticketsuccess.home": "Startseite",
		"ticketsuccess.email": "Tickets an E-Mail gesendet.",
		"ticketsuccess.artikel": "Artikel",
		"ticketsuccess.menge": "Menge",
		"ticketsuccess.preis": "Preis",
		"ticketsuccess.gesamtbetrag": "Gesamtbetrag",
		"ticketsuccess.ticketCode": "Ticket / Buchungscode",
		"ticketsuccess.qrHint": "Am Einlass scannen – gilt als Ticket",

		"mytickets.title": "Meine Tickets",
		"mytickets.welcome": "Ihre Buchungen auf einen Blick",
		"mytickets.loading": "Tickets werden geladen…",
		"mytickets.error": "Tickets konnten nicht geladen werden. Bitte später erneut versuchen.",
		"mytickets.section.upcoming": "Kommende Vorstellungen",
		"mytickets.section.menus": "Meine Menüs & Snacks",
		"mytickets.empty.tickets": "Noch keine Tickets",
		"mytickets.empty.ticketsSubtitle": "Buchen Sie Ihr nächstes Kinoerlebnis.",
		"mytickets.empty.ticketsLink": "Filme ansehen",
		"mytickets.empty.menus": "Noch keine Menübestellungen",
		"mytickets.empty.menusSubtitle": "Snacks und Getränke erscheinen hier nach dem Kauf.",
		"mytickets.empty.menusLink": "Snacks durchstöbern",
		"mytickets.toFilm": "Zum Film",

		"favorites.title": "Favoriten",
		"favorites.welcome": "Ihre Merkliste",
		"favorites.loading": "Favoriten werden geladen…",
		"favorites.error": "Favoriten konnten nicht geladen werden. Bitte später erneut versuchen.",
		"favorites.empty.title": "Noch keine Favoriten",
		"favorites.empty.subtitle": "Speichern Sie Filme in Ihrer Merkliste.",
		"favorites.empty.link": "Zum Programm",
		"favorites.remove": "Aus Favoriten entfernen",
		"favorites.bookTickets": "Tickets buchen",

		"bookinghistory.title": "Buchungshistorie",
		"bookinghistory.welcome": "Vergangene Reservierungen und Einkäufe.",
		"bookinghistory.loading": "Wird geladen…",
		"bookinghistory.error": "Buchungen konnten nicht geladen werden. Bitte später erneut versuchen.",
		"bookinghistory.empty.title": "Keine vergangenen Buchungen",
		"bookinghistory.empty.subtitle": "Hier erscheinen abgeschlossene Kinobesuche.",
		"bookinghistory.empty.link": "Filme ansehen",
		"bookinghistory.loadingText": "Buchungen werden geladen…",
		"bookinghistory.errorText": "Buchungshistorie konnte nicht geladen werden. Bitte später erneut versuchen.",

		"usermenu.myAccount": "Mein Konto",
		"usermenu.profile": "Profil",
		"usermenu.myTickets": "Meine Tickets",
		"usermenu.favorites": "Favoriten",
		"usermenu.history": "Buchungshistorie",
		"usermenu.logout": "Abmelden",
		"usermenu.login": "Anmelden",
		"usermenu.register": "Registrieren",
		"usermenu.user": "Benutzer",
		"usermenu.info": "Info & Hilfe",

		"profile.welcome": "Willkommen, {{name}}",
		"profile.section.tickets": "Tickets & Buchungen",
		"profile.tickets.desc": "Ihre gebuchten Kinotickets einsehen und verwalten",
		"profile.history.desc": "Vergangene Reservierungen und Einkäufe",
		"profile.section.account": "Konto",
		"profile.favorites.desc": "Gespeicherte Filme und Merkliste",

		"common.min": "Min.",
		"common.eur": "€",
		"common.back": "Zurück",
		"common.continue": "Weiter",
		"common.cancel": "Abbrechen",
		"common.save": "Speichern",
		"common.delete": "Löschen",
		"common.edit": "Bearbeiten",
		"common.close": "Schließen",
		"common.loading": "Wird geladen…",
		"common.error": "Ein Fehler ist aufgetreten",

		"footer.copyright": "© 2026 Demo-Version von Orhan Yilmaz – alle Rechte vorbehalten; keine kommerzielle Nutzung.",

		"menu.addToCart": "In den Warenkorb",
		"menu.extraGrosses.name": "Extra Großes Menu",
		"menu.extraGrosses.description": "Extra großes Menü mit Getränk",
		"menu.extra.name": "Extra Menu",
		"menu.extra.description": "Extra Menü mit Getränk",
		"menu.grosses.name": "Großes Menu",
		"menu.grosses.description": "Großes Menü mit Getränk",
		"menu.kinder.name": "Kinder Menu",
		"menu.kinder.description": "Kinderfreundliches Menü",
		"menu.rioSanto.name": "Rio Santo Menu",
		"menu.rioSanto.description": "Rio Santo Spezial Menü",
		"menu.drink.description": "Menü mit Getränk",
		"menu.drinks.cocaCola": "Coca Cola",
		"menu.drinks.fanta": "Fanta",
		"menu.drinks.fruchtsaft": "Fruchtsaft",
		"menu.drinks.iceTea": "Ice Tea",
		"menu.drinks.wasser": "Wasser",

		"help.title": "Info & Hilfe",
		"help.subtitle": "Bei Fragen helfen wir gern.",
		"help.faq.title": "Häufig gestellte Fragen",
		"help.faq.ticketPurchase.question": "Wie kaufe ich Tickets?",
		"help.faq.ticketPurchase.answer": "Wählen Sie einen Film, Ihr Kino, Datum und Vorstellungszeit aus, dann wählen Sie Ihre Plätze. Fügen Sie Tickets zum Warenkorb hinzu und gehen Sie zur Zahlung.",
		"help.faq.payment.question": "Welche Zahlungsmethoden werden akzeptiert?",
		"help.faq.payment.answer": "Wir akzeptieren Kreditkarten (Visa, Mastercard) und Debitkarten. Die Zahlung wird sicher verarbeitet.",
		"help.faq.cancellation.question": "Kann ich meine Tickets stornieren oder zurückgeben?",
		"help.faq.cancellation.answer": "Tickets können bis zu 2 Stunden vor Vorstellungsbeginn storniert werden. Rückerstattungen werden innerhalb von 5-7 Werktagen bearbeitet.",
		"help.faq.seats.question": "Wie wähle ich Plätze aus?",
		"help.faq.seats.answer": "Nach der Auswahl einer Vorstellungszeit sehen Sie die Sitzplatzkarte. Klicken Sie auf verfügbare Plätze, um sie auszuwählen. Sie können bis zu 6 Plätze pro Buchung auswählen.",
		"help.faq.membership.question": "Was ist CinemoR Club?",
		"help.faq.membership.answer": "CinemoR Club ist unser Treueprogramm. Mitglieder sammeln Punkte bei jedem Kauf und erhalten exklusive Vorteile und Rabatte.",
		"help.contact.title": "Kontakt",
		"help.contact.email.title": "E-Mail",
		"help.contact.phone.title": "Telefon",
		"help.contact.phone.hours": "Mo–So: 9:00 – 22:00 Uhr",
		"help.contact.address.title": "Adresse",
		"help.contact.hours.title": "Öffnungszeiten",
		"help.contact.hours.content": "Mo–So: 10:00 – 24:00 Uhr",
		"help.support.title": "Support",
		"help.support.description": "Benötigen Sie weitere Hilfe? Überprüfen Sie Ihr Konto oder kontaktieren Sie unser Support-Team.",
		"help.support.myTickets": "Meine Tickets",
		"help.support.bookingHistory": "Buchungshistorie",
		"help.support.profile": "Mein Profil",

		"login.title": "Anmelden",
		"login.subtitle": "Sie haben noch kein Konto?",
		"login.registerLink": "Jetzt registrieren",
		"login.email": "E-Mail",
		"login.password": "Passwort",
		"login.showPassword": "Passwort anzeigen",
		"login.hidePassword": "Passwort verbergen",
		"login.forgotPassword": "Passwort vergessen?",
		"login.submit": "Anmelden",
		"login.loading": "Wird geladen...",
		"login.error": "Login fehlgeschlagen",
		"login.guestPurchase": "Oder Ticketkauf ohne Anmeldung",
		"login.noAccount": "Noch kein Konto?",
		"login.registerNow": "Jetzt kostenlos registrieren",

		"register.title": "CinemoR ID REGISTRIERUNG",
		"register.subtitle": "Sie haben bereits eine CinemoR ID?",
		"register.loginLink": "Melden Sie sich hier an.",
		"register.requiredFields": "*Pflichtfelder",
		"register.firstName": "Vorname",
		"register.lastName": "Nachname",
		"register.email": "E-Mail",
		"register.password": "Passwort",
		"register.confirmPassword": "Passwort bestätigen",
		"register.showPassword": "Passwort anzeigen",
		"register.hidePassword": "Passwort verbergen",
		"register.strongPassword": "Starkes Passwort",
		"register.acceptTerms": "Ich akzeptiere die Allgemeinen Geschäftsbedingungen",
		"register.showTerms": "Allgemeine Geschäftsbedingungen anzeigen",
		"register.disclaimer": "Diese Seite verwendet hCaptcha. Weitere Informationen finden Sie unter \"Rechtlicher Hinweis\" oder \"Datenschutz\".",
		"register.submit": "Jetzt registrieren",
		"register.loading": "Wird geladen...",
		"register.error.password": "Passwort muss mindestens 8 Zeichen lang sein und Groß-/Kleinbuchstaben, Zahl und Sonderzeichen enthalten.",
		"register.error.passwordMismatch": "Passwörter stimmen nicht überein",
		"register.error.terms": "Bitte akzeptieren Sie die Allgemeinen Geschäftsbedingungen",
		"register.error.failed": "Registrierung fehlgeschlagen",

		"checkout.title": "Weiter zur Zahlung",
		"checkout.welcome": "Film: {{movie}} · {{seats}} Platz/Plätze · {{price}} €",
		"checkout.loggedIn": "Angemeldet",
		"checkout.continue": "Weiter zur Zahlung",
		"checkout.logout": "Abmelden",
		"checkout.choose": "Wie möchten Sie fortfahren?",
		"checkout.login": "Anmelden",
		"checkout.loginDesc": "Mit E-Mail anmelden und zur Zahlung",
		"checkout.register": "Registrieren",
		"checkout.registerDesc": "Neues Konto anlegen, dann zahlen",
		"checkout.guest": "Als Gast fortfahren",
		"checkout.guestDesc": "Ohne Konto zur Zahlung",
		"checkout.back": "← Zurück zur Sitzplatzwahl",

		"forgotpassword.title": "Passwort vergessen",
		"forgotpassword.subtitle": "Geben Sie Ihre E-Mail-Adresse ein. Wir senden Ihnen einen Link zum Zurücksetzen.",
		"forgotpassword.email": "E-Mail-Adresse",
		"forgotpassword.send": "Link senden",
		"forgotpassword.sending": "Wird gesendet...",
		"forgotpassword.success": "E-Mail gesendet. Bitte Postfach prüfen.",
		"forgotpassword.back": "Zurück zur Anmeldung",
		"forgotpassword.error.failed": "Anfrage fehlgeschlagen. Bitte E-Mail prüfen.",
		"forgotpassword.error.notFound": "Diese E-Mail-Adresse ist nicht registriert.",
		"forgotpassword.error.connection": "Verbindungsfehler. Bitte später erneut versuchen.",

		"resetpassword.title": "Neues Passwort",
		"resetpassword.subtitle": "Geben Sie Ihr neues Passwort ein (mindestens 6 Zeichen).",
		"resetpassword.newPassword": "Neues Passwort",
		"resetpassword.confirmPassword": "Passwort bestätigen",
		"resetpassword.save": "Passwort speichern",
		"resetpassword.saving": "Wird gespeichert...",
		"resetpassword.success": "Passwort wurde geändert. Sie können sich jetzt anmelden.",
		"resetpassword.back": "Zurück zur Anmeldung",
		"resetpassword.requestNew": "Neuen Link anfordern",
		"resetpassword.error.invalid": "Ungültiger Link. Bitte fordern Sie einen neuen Link an.",
		"resetpassword.error.mismatch": "Passwörter stimmen nicht überein.",
		"resetpassword.error.short": "Passwort muss mindestens 6 Zeichen haben.",
		"resetpassword.error.expired": "Link ungültig oder abgelaufen. Bitte Passwort erneut anfordern.",
		"resetpassword.error.connection": "Verbindungsfehler. Bitte später erneut versuchen.",

		"common.time": "Uhr",
		"common.user": "Benutzer",
		"common.loadingMovie": "Film wird geladen...",
		"common.loadingShowtimes": "Vorstellungen werden geladen...",
	},
};

export const LanguageProvider = ({ children }) => {
	const [language, setLanguage] = useState(() => {
		if (typeof window === "undefined") return "de";
		return localStorage.getItem("cinemor-lang") || "de";
	});

	useEffect(() => {
		if (typeof window === "undefined") return;
		localStorage.setItem("cinemor-lang", language);
	}, [language]);

	const t = useMemo(
		() => (key, fallback) => {
			const dict = translations[language] || {};
			const value = dict[key];
			if (typeof value === "string") return value;
			const deDict = translations.de || {};
			if (deDict[key]) return deDict[key];
			return fallback || key;
		},
		[language],
	);

	const value = useMemo(
		() => ({
			language,
			setLanguage,
			t,
		}),
		[language, t],
	);

	return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
